### ISSUE TITLE
What's the difference between soft and highlight theme?

### ISSUE THREAD

**Issue by tristone13th** [thiagolucio/ubuntuVscode#1]
It seems that these two themes are the same.

**Comment by thiagolucio** [comment]
> It seems that these two themes are the same.

In fact, they are not. What differentiates the two with lighter tones is precisely the background color. On certain monitors, you won't notice the difference but if your monitor is a retina screen or uses HDR this difference between the themes with the final name "Soft Dark" and "Dark Highlight" will be considered significant.

I created them due to the fact that some people asked me to and as there were two colors that practically tied, I decided to add these two to please most people.

Take a look if you have the last version. The last version it's 0.0.6.

**Comment by tristone13th** [comment]
> > It seems that these two themes are the same.
> 
> In fact, they are not. What differentiates the two with lighter tones is precisely the background color. On certain monitors, you won't notice the difference but if your monitor is a retina screen or uses HDR this difference between the themes with the final name "Soft Dark" and "Dark Highlight" will be considered significant.
> 
> I created them due to the fact that some people asked me to and as there were two colors that practically tied, I decided to add these two to please most people.
> 
> Take a look if you have the last version. The last version it's 0.0.6.

Got it, thanks for your explanation.

**Comment by thiagolucio** [comment]
> > > It seems that these two themes are the same.
> > 
> > 
> > In fact, they are not. What differentiates the two with lighter tones is precisely the background color. On certain monitors, you won't notice the difference but if your monitor is a retina screen or uses HDR this difference between the themes with the final name "Soft Dark" and "Dark Highlight" will be considered significant.
> > I created them due to the fact that some people asked me to and as there were two colors that practically tied, I decided to add these two to please most people.
> > Take a look if you have the last version. The last version it's 0.0.6.
> 
> Got it, thanks for your explanation.

Always Welcome tristone!
